{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "a368ded9",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "SystemExit",
     "evalue": "0",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 0\n"
     ]
    }
   ],
   "source": [
    "# Required imports\n",
    "import sys\n",
    "from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QFileDialog, QVBoxLayout, QGraphicsView, QGraphicsScene, QTextBrowser, QScrollArea, QLineEdit, QLabel, QHBoxLayout, QGridLayout, QCheckBox\n",
    "from PyQt5.QtGui import QPen, QColor\n",
    "from PyQt5.QtCore import Qt\n",
    "import ezdxf\n",
    "import os\n",
    "import qdarktheme\n",
    "\n",
    "# Parses input file to extract entities relative to gcode\n",
    "def parse_dxf_file(file_path):\n",
    "    parsed_data = []\n",
    "    doc = ezdxf.readfile(file_path)\n",
    "    for entity in doc.modelspace():\n",
    "        if entity.dxftype() == 'LINE':\n",
    "            start_point = entity.dxf.start\n",
    "            end_point = entity.dxf.end\n",
    "            parsed_data.append({\n",
    "                'type': 'LINE',\n",
    "                'start_point': (start_point.x, start_point.y),\n",
    "                'end_point': (end_point.x, end_point.y)\n",
    "            })\n",
    "        elif entity.dxftype() == 'CIRCLE':\n",
    "            center = entity.dxf.center\n",
    "            radius = entity.dxf.radius\n",
    "            parsed_data.append({\n",
    "                'type': 'CIRCLE',\n",
    "                'center_point': (center.x, center.y),\n",
    "                'radius': radius\n",
    "            })\n",
    "        elif entity.dxftype() == 'ARC':\n",
    "            center = entity.dxf.center\n",
    "            radius = entity.dxf.radius\n",
    "            start_angle = entity.dxf.start_angle\n",
    "            end_angle = entity.dxf.end_angle\n",
    "            parsed_data.append({\n",
    "                'type': 'ARC',\n",
    "                'center_point': (center.x, center.y),\n",
    "                'radius': radius,\n",
    "                'start_angle': start_angle,\n",
    "                'end_angle': end_angle\n",
    "            })\n",
    "        elif entity.dxftype() == 'LWPOLYLINE':\n",
    "            polyline_data = []\n",
    "            for vertex in entity.points():\n",
    "                polyline_data.append((vertex.x, vertex.y))\n",
    "            parsed_data.append({\n",
    "                'type': 'POLYLINE',\n",
    "                'vertices': polyline_data\n",
    "            })\n",
    "\n",
    "    return parsed_data\n",
    "\n",
    "# block num space padding logic\n",
    "def blockNumPad(blockNum):\n",
    "    blockNumStr = \"\"\n",
    "    if blockNum < 10:\n",
    "        blockNumStr = \"    0\" + str(blockNum)\n",
    "    elif blockNum < 100:\n",
    "        blockNumStr = \"    \" + str(blockNum)\n",
    "    else:\n",
    "        blockNumStr = \"   \" + str(blockNum)\n",
    "    return blockNumStr\n",
    "\n",
    "# Parses DXF data into Emco supported GCode\n",
    "def generate_gcode_from_dxf(parsed_data, isUseM3M5Checked):\n",
    "    # starting blocks\n",
    "    gcode = []\n",
    "    blockNum = 0\n",
    "    gcode.append(f'%\\n')\n",
    "    gcode.append(f'    N` G`   X `    Z `  F`  H\\n')\n",
    "    if isUseM3M5Checked:\n",
    "        gcode.append(f'{blockNumPad(blockNum)}M03\\n')\n",
    "\n",
    "    # generate main gcode blocks\n",
    "    blockNum +=1\n",
    "    for entity in parsed_data:\n",
    "        toAppend = \"\"\n",
    "        if entity['type'] == 'LINE':\n",
    "            start_x, start_y = entity['start_point']\n",
    "            end_x, end_y = entity['end_point']\n",
    "            gcodeToAdd = (f'01 X{end_x:.3f} Y{end_y:.3f}')\n",
    "        elif entity['type'] == 'CIRCLE':\n",
    "            center_x, center_y = entity['center_point']\n",
    "            radius = entity['radius']\n",
    "            gcodeToAdd = (f'02 X{center_x:.3f} Y{center_y:.3f} R{radius:.3f}')\n",
    "            gcodeToAdd = (f'03 X{center_x:.3f} Y{center_y:.3f} R{radius:.3f}')\n",
    "        elif entity['type'] == 'ARC':\n",
    "            center_x, center_y = entity['center_point']\n",
    "            radius = entity['radius']\n",
    "            start_angle = entity['start_angle']\n",
    "            end_angle = entity['end_angle']\n",
    "            if start_angle < end_angle:\n",
    "                gcodeToAdd = (f'M02 X{center_x:.3f} Y{center_y:.3f} R{radius:.3f} A{start_angle:.3f} B{end_angle:.3f}')\n",
    "            else:\n",
    "                gcodeToAdd = (f'M03 X{center_x:.3f} Y{center_y:.3f} R{radius:.3f} A{start_angle:.3f} B{end_angle:.3f}')\n",
    "        elif entity['type'] == 'POLYLINE':\n",
    "            vertices = entity['vertices']\n",
    "            for vertex in vertices:\n",
    "                x, y = vertex\n",
    "                gcodeToAdd = (f'01 X{x:.3f} Y{y:.3f}')\n",
    "            \n",
    "        \n",
    "        # append to output\n",
    "        toAppend = blockNumPad(blockNum) + \" \" + gcodeToAdd + \"\\n\"\n",
    "        gcode.append(toAppend)\n",
    "        blockNum += 1\n",
    "           \n",
    "    # ending blocks\n",
    "    if isUseM3M5Checked:\n",
    "        gcode.append(f'{blockNumPad(blockNum)}M05\\n')\n",
    "        blockNum +=1\n",
    "    gcode.append(f'{blockNumPad(blockNum)}M30\\n')\n",
    "    gcode.append(f'   M\\n')\n",
    "    return gcode\n",
    "\n",
    "# Determins the max DXF size for scaling DXF preview \n",
    "def calculate_drawing_extents(entities):\n",
    "    min_x = float('inf')\n",
    "    min_y = float('inf')\n",
    "    max_x = float('-inf')\n",
    "    max_y = float('-inf')\n",
    "\n",
    "    for entity in entities:\n",
    "        if entity['type'] == 'LINE':\n",
    "            start_x, start_y = entity['start_point']\n",
    "            end_x, end_y = entity['end_point']\n",
    "            min_x = min(min_x, start_x, end_x)\n",
    "            max_x = max(max_x, start_x, end_x)\n",
    "            min_y = min(min_y, start_y, end_y)\n",
    "            max_y = max(max_y, start_y, end_y)\n",
    "        elif entity['type'] == 'CIRCLE':\n",
    "            center_x, center_y = entity['center_point']\n",
    "            radius = entity['radius']\n",
    "            min_x = min(min_x, center_x - radius)\n",
    "            max_x = max(max_x, center_x + radius)\n",
    "            min_y = min(min_y, center_y - radius)\n",
    "            max_y = max(max_y, center_y + radius)\n",
    "        elif entity['type'] == 'ARC':\n",
    "            center_x, center_y = entity['center_point']\n",
    "            radius = entity['radius']\n",
    "            start_angle = entity['start_angle']\n",
    "            end_angle = entity['end_angle']\n",
    "            min_x = min(min_x, center_x - radius)\n",
    "            max_x = max(max_x, center_x + radius)\n",
    "            min_y = min(min_y, center_y - radius)\n",
    "            max_y = max(max_y, center_y + radius)\n",
    "        elif entity['type'] == 'POLYLINE':\n",
    "            for vertex in entity['vertices']:\n",
    "                x, y = vertex\n",
    "                min_x = min(min_x, x)\n",
    "                max_x = max(max_x, x)\n",
    "                min_y = min(min_y, y)\n",
    "                max_y = max(max_y, y)\n",
    "\n",
    "    return min_x, min_y, max_x, max_y\n",
    "\n",
    "# Emco Processor GUI\n",
    "class DXFParserGUI(QWidget):\n",
    "    \n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.initUI()\n",
    "        self.file_path = \"\"\n",
    "        self.output_code = \"\"\n",
    "\n",
    "    def initUI(self):\n",
    "        layout = QVBoxLayout()\n",
    "\n",
    "        # Display the DXF drawing\n",
    "        self.view = QGraphicsView(self)\n",
    "        self.scene = QGraphicsScene()\n",
    "        self.view.setScene(self.scene)\n",
    "        layout.addWidget(self.view)\n",
    "\n",
    "        # Open DXF file button\n",
    "        self.btn_open = QPushButton(\"Open DXF File\")\n",
    "        self.btn_open.clicked.connect(self.openFile)\n",
    "        layout.addWidget(self.btn_open)\n",
    "\n",
    "        # Create a grid layout for labels and text boxes\n",
    "        grid_layout = QGridLayout()\n",
    "\n",
    "        # Stock Radius input\n",
    "        self.stock_radius_label = QLabel(\"Stock Radius (mm):\")\n",
    "        self.stock_radius_input = QLineEdit()\n",
    "        grid_layout.addWidget(self.stock_radius_label, 0, 0)\n",
    "        grid_layout.addWidget(self.stock_radius_input, 0, 1)\n",
    "\n",
    "        # Roughing Feedrate input\n",
    "        self.roughing_feedrate_label = QLabel(\"Roughing Feedrate (mm/min):\")\n",
    "        self.roughing_feedrate_input = QLineEdit()\n",
    "        grid_layout.addWidget(self.roughing_feedrate_label, 0, 3)\n",
    "        grid_layout.addWidget(self.roughing_feedrate_input, 0, 4)\n",
    "\n",
    "        # Roughing Stepdown input\n",
    "        self.roughing_stepdown_label = QLabel(\"Roughing Stepdown (mm):\")\n",
    "        self.roughing_stepdown_input = QLineEdit()\n",
    "        grid_layout.addWidget(self.roughing_stepdown_label, 0, 5)\n",
    "        grid_layout.addWidget(self.roughing_stepdown_input, 0, 6)\n",
    "\n",
    "        # Finishing Feedrate input\n",
    "        self.finishing_feedrate_label = QLabel(\"Finishing Feedrate (mm/min):\")\n",
    "        self.finishing_feedrate_input = QLineEdit()\n",
    "        grid_layout.addWidget(self.finishing_feedrate_label, 0, 7)\n",
    "        grid_layout.addWidget(self.finishing_feedrate_input, 0, 8)\n",
    "\n",
    "        # Finishing Stepdown input\n",
    "        self.finishing_stepdown_label = QLabel(\"Finishing Stepdown (mm):\")\n",
    "        self.finishing_stepdown_input = QLineEdit()\n",
    "        grid_layout.addWidget(self.finishing_stepdown_label, 0, 9)\n",
    "        grid_layout.addWidget(self.finishing_stepdown_input, 0, 10)\n",
    "        \n",
    "        # Use M3/M5 toggle button\n",
    "        self.use_m3_m5_checkbox = QCheckBox(\"Use M3/M5\")\n",
    "        grid_layout.addWidget(self.use_m3_m5_checkbox, 1, 0, 1, 1)\n",
    "\n",
    "        # Add the grid layout to the main layout\n",
    "        layout.addLayout(grid_layout)\n",
    "\n",
    "        # Scrollable G-code display\n",
    "        self.gcode_browser = QTextBrowser(self)\n",
    "        self.scroll_area = QScrollArea(self)\n",
    "        self.scroll_area.setWidget(self.gcode_browser)\n",
    "        self.gcode_browser.setFixedWidth(1735)\n",
    "        self.gcode_browser.setFixedHeight(575)\n",
    "        layout.addWidget(self.scroll_area)\n",
    "        \n",
    "        # Set the font size for the QTextBrowser\n",
    "        font = self.gcode_browser.currentFont()\n",
    "        font.setPointSize(14)  # Adjust the font size (in points) as needed\n",
    "        self.gcode_browser.setFont(font)\n",
    "        \n",
    "        # Create a grid layout for generate and save buttons\n",
    "        grid_layout2 = QGridLayout()\n",
    "\n",
    "        # Generate G-code button\n",
    "        self.btn_gen = QPushButton(\"Generate G-code\")\n",
    "        self.btn_gen.clicked.connect(self.generateGCode)\n",
    "        grid_layout2.addWidget(self.btn_gen, 0, 0)\n",
    "        \n",
    "        # Save G-code button\n",
    "        self.btn_save = QPushButton(\"Save G-code\")\n",
    "        self.btn_save.clicked.connect(self.saveGCode)\n",
    "        grid_layout2.addWidget(self.btn_save, 0, 1)\n",
    "        \n",
    "        # Add the grid layout to the main layout\n",
    "        layout.addLayout(grid_layout2)\n",
    "\n",
    "        self.setLayout(layout)\n",
    "        self.setGeometry(100, 100, 1600, 1200)\n",
    "        self.setWindowTitle(\"DXF Parser\")\n",
    "        self.show()\n",
    "        \n",
    "##############################################################################################\n",
    "#################################  CALLBACK FUNCTIONS  #######################################\n",
    "##############################################################################################\n",
    "\n",
    "    # Function to get the value of the Use M3/M5 checkbox\n",
    "    def isUseM3M5Checked(self):\n",
    "        return self.use_m3_m5_checkbox.isChecked()\n",
    "    \n",
    "    # Opens DXF file from your computer\n",
    "    def openFile(self):\n",
    "        options = QFileDialog.Options()\n",
    "        self.file_path, _ = QFileDialog.getOpenFileName(self, \"Open DXF File\", \"\", \"DXF Files (*.dxf);;All Files (*)\", options=options)\n",
    "        if self.file_path:\n",
    "            entities = parse_dxf_file(self.file_path)\n",
    "            self.parseAndDisplayDXF(entities)\n",
    "           \n",
    "    # Starts gcode generating process\n",
    "    def generateGCode(self):\n",
    "        entities = parse_dxf_file(self.file_path)\n",
    "        self.output_code = generate_gcode_from_dxf(entities, self.isUseM3M5Checked())\n",
    "        self.gcode_browser.clear()\n",
    "        self.gcode_browser.append(''.join(self.output_code))\n",
    "            \n",
    "    # Displays DXF and scales uniformly to fit screen\n",
    "    def parseAndDisplayDXF(self, entities):\n",
    "        self.scene.clear()\n",
    "        # Get the drawing extents for scaling\n",
    "        min_x, min_y, max_x, max_y = calculate_drawing_extents(entities)\n",
    "        drawing_width = max_x - min_x\n",
    "        drawing_height = max_y - min_y\n",
    "        scale_factor = 1000 / max(drawing_width, drawing_height)  # Adjust the scale as needed\n",
    "\n",
    "        for entity in entities:\n",
    "            if entity['type'] == 'LINE':\n",
    "                start_x, start_y = entity['start_point']\n",
    "                end_x, end_y = entity['end_point']\n",
    "                line = self.scene.addLine(start_x * scale_factor, -start_y * scale_factor, end_x * scale_factor, -end_y * scale_factor)\n",
    "                pen = QPen(QColor(0, 0, 255))\n",
    "                line.setPen(pen)\n",
    "            elif entity['type'] == 'CIRCLE':\n",
    "                center_x, center_y = entity['center_point']\n",
    "                radius = entity['radius']\n",
    "                circle = self.scene.addEllipse((center_x - radius) * scale_factor, (-center_y - radius) * scale_factor, radius * 2 * scale_factor, radius * 2 * scale_factor)\n",
    "                pen = QPen(QColor(0, 0, 255))\n",
    "                circle.setPen(pen)\n",
    "            elif entity['type'] == 'POLYLINE':\n",
    "                vertices = entity['vertices']\n",
    "                polyline = QGraphicsView()\n",
    "                poly_scene = QGraphicsScene()\n",
    "                polyline.setScene(poly_scene)\n",
    "                pen = QPen(QColor(0, 0, 255))\n",
    "                for i in range(len(vertices) - 1):\n",
    "                    start_x, start_y = vertices[i]\n",
    "                    end_x, end_y = vertices[i + 1]\n",
    "                    line = poly_scene.addLine(start_x * scale_factor, -start_y * scale_factor, end_x * scale_factor, -end_y * scale_factor)\n",
    "                    line.setPen(pen)\n",
    "                self.view.setScene(self.scene)\n",
    "\n",
    "    # Saves gcode file to your computer\n",
    "    def saveGCode(self):\n",
    "        filename, _ = QFileDialog.getSaveFileName(self, filter=\"*.cnc\")\n",
    "        if filename:\n",
    "            f = open(filename, 'w')\n",
    "            toWrite = \"\"\n",
    "            toWrite = toWrite.join(self.output_code) \n",
    "            f.write(toWrite)\n",
    "            self.setWindowTitle(str(os.path.basename(filename)) + \" - Notepad Alpha\")\n",
    "            f.close()\n",
    "       \n",
    "def main():\n",
    "    app = QApplication(sys.argv)\n",
    "    qdarktheme.setup_theme()\n",
    "    window = DXFParserGUI()\n",
    "    sys.exit(app.exec_())\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "24fb78c8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a45c666",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
